services:

  db:
    image: mysql:8.0
    container_name: salessavvy-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "ganesh"
      MYSQL_DATABASE: salesproject
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -p$${MYSQL_ROOT_PASSWORD} --silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: salessavvy-app
    restart: unless-stopped
    ports:
      - "9090:9090"
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/salesproject
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ganesh
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: your-very-long-secure-secret-key-for-production-1234567890123451234567890
      JWT_EXPIRATION: "3600000"
      RAZORPAY_KEY_ID: rzp_test_RqluYPxeaWy1jI
      RAZORPAY_KEY_SECRET: JN3SwHuiEycdD0adT8zm53kH

volumes:
  mysql_data:
